/**
 * @file City Traffic Intelligence & Control — shared constants and data-mode
 * vocabulary.
 *
 * The single most important export here is {@link DATA_MODES}. The platform
 * mixes real feeds (TomTom flow, configured CCTV, mapped ALPR infrastructure)
 * with generated ones (the signal simulator, the scenario engine, the vehicle
 * detector stub). Nothing may present generated values as measured ones, so
 * every fact that crosses a module boundary carries a mode tag taken from this
 * table. See DATA-SOURCES.md.
 *
 * Cesium-free and dependency-free on purpose: this module is imported by the
 * browser layer, the server provider and the unit tests alike.
 *
 * @module traffic-control/policy
 */

// ─── Data modes ────────────────────────────────────────────────────────────

/**
 * Provenance vocabulary for every fact the platform renders.
 *
 * - `live` — measured upstream right now (TomTom flow, a configured CCTV feed).
 * - `simulated` — generated by this platform's own simulator/scenario engine.
 * - `estimated` — derived by this platform from measured inputs (a queue
 *   inferred from a measured speed is estimated, not live).
 * - `unavailable` — a source was expected and did not answer.
 * - `unconfigured` — the capability exists but no source/key is wired up.
 *
 * @const {Object<string,string>}
 */
export const DATA_MODES = Object.freeze({
  live: 'live',
  simulated: 'simulated',
  estimated: 'estimated',
  unavailable: 'unavailable',
  unconfigured: 'unconfigured',
});

/** @const {string[]} Every mode, in presentation order. */
export const DATA_MODE_ORDER = Object.freeze([
  DATA_MODES.live,
  DATA_MODES.simulated,
  DATA_MODES.estimated,
  DATA_MODES.unavailable,
  DATA_MODES.unconfigured,
]);

const MODE_LABELS = Object.freeze({
  live: 'LIVE',
  simulated: 'SIMULATED',
  estimated: 'ESTIMATED',
  unavailable: 'UNAVAILABLE',
  unconfigured: 'UNCONFIGURED',
});

/**
 * Uppercase chip text for a composed source, e.g. `LIVE — TomTom`.
 * @param {string} mode - One of {@link DATA_MODES}.
 * @param {string} [source] - Human-readable source name.
 * @returns {string}
 */
export function dataModeLabel(mode, source) {
  const word = MODE_LABELS[mode] || 'UNKNOWN';
  return source ? `${word} — ${source}` : word;
}

/**
 * Whether a value with this mode may be described to an operator as real.
 * @param {string} mode
 * @returns {boolean}
 */
export function isMeasured(mode) {
  return mode === DATA_MODES.live;
}

// ─── Operating modes ───────────────────────────────────────────────────────

/**
 * What the platform is allowed to DO, not what it is showing.
 *
 * - `recommendation` — analyse and advise; no state changes.
 * - `simulation` — apply changes to the built-in signal simulator only.
 * - `authorized-control` — would drive a configured, authorized controller API.
 *
 * Nothing in this prototype reaches `authorized-control`: no real controller
 * integration is configured, so the server refuses to enter it and the UI
 * cannot select it. That refusal is the rule-6 guarantee, enforced in one place
 * rather than asserted in documentation.
 *
 * @const {Object<string,string>}
 */
export const OPERATING_MODES = Object.freeze({
  recommendation: 'recommendation',
  simulation: 'simulation',
  authorizedControl: 'authorized-control',
});

/** @const {string[]} */
export const OPERATING_MODE_ORDER = Object.freeze([
  OPERATING_MODES.recommendation,
  OPERATING_MODES.simulation,
  OPERATING_MODES.authorizedControl,
]);

/** @const {string} Default mode for a fresh prototype session. */
export const DEFAULT_OPERATING_MODE = OPERATING_MODES.simulation;

// ─── Signal timing ─────────────────────────────────────────────────────────

/** @const {string[]} Cardinal approach directions, in phase-pair order. */
export const DIRECTIONS = Object.freeze(['N', 'S', 'E', 'W']);

/** @const {string[]} The two phase groups a 4-way intersection supports. */
export const PHASE_GROUPS = Object.freeze(['NS', 'EW']);

/**
 * Map an approach direction to its axis. Two approaches on the same axis run
 * in parallel and never conflict; approaches on different axes cross and
 * always conflict. This one function is what makes the conflict invariant
 * provable rather than asserted.
 * @param {string} direction
 * @returns {'NS'|'EW'|null}
 */
export function approachAxis(direction) {
  if (direction === 'N' || direction === 'S') return 'NS';
  if (direction === 'E' || direction === 'W') return 'EW';
  return null;
}

/** @const {Object<string,string[]>} The two approaches each phase group serves. */
export const PHASE_GROUP_APPROACHES = Object.freeze({
  NS: Object.freeze(['N', 'S']),
  EW: Object.freeze(['E', 'W']),
});

/** @const {string[]} The signal states an approach can report. */
export const SIGNAL_STATES = Object.freeze(['green', 'amber', 'red']);

/** @const {string[]} Intersection controller phases, in transition order. */
export const CONTROLLER_PHASES = Object.freeze([
  'green',
  'amber',
  'all-red',
  'fault',
]);

/** @const {number} ms — standard amber clearance interval. */
export const AMBER_MS = 3000;

/** @const {number} ms — all-red clearance interval (the safety gap). */
export const ALL_RED_MS = 2000;

/** @const {number} ms — minimum green any phase may be shortened to. */
export const MIN_GREEN_MS = 8000;

/** @const {number} ms — maximum green a single phase may hold. */
export const MAX_GREEN_MS = 75000;

/** @const {number} ms — green a fresh/unknown intersection starts on. */
export const DEFAULT_GREEN_MS = 30000;

/** @const {number} ms — an emergency priority hold before it is released. */
export const EMERGENCY_HOLD_MS = 18000;

/** @const {number} ms — grace period after a vehicle clears before restoring. */
export const EMERGENCY_RELEASE_GRACE_MS = 4000;

// ─── Traffic analysis thresholds ───────────────────────────────────────────

/** @const {number} TomTom traffic_level at/above which flow reads free. */
export const FREE_FLOW_LEVEL = 0.85;

/** @const {number} TomTom traffic_level at/above which flow reads slow. */
export const SLOW_FLOW_LEVEL = 0.55;

/** @const {number} veh/km/lane at/above which density reads jammed. */
export const JAM_DENSITY_VPKPL = 130;

/** @const {number} veh/km/lane at/above which density reads congested. */
export const CONGESTED_DENSITY_VPKPL = 25;

/** @const {number} Seconds of average delay at/above which LOS is F. */
export const LOS_F_DELAY_S = 80;

/** @const {number} Default free-flow speed (m/s) when a class has none. */
export const DEFAULT_FREE_FLOW_MPS = 13.9;

/**
 * Free-flow speed in m/s by OSM `highway` class. Mirrors the traffic layer's
 * own `SPEED_MPS` table so a road's baseline does not change when it is read
 * through the control plane instead of the visual layer.
 * @const {Object<string,number>}
 */
export const FREE_FLOW_MPS_BY_ROAD_CLASS = Object.freeze({
  motorway: 30,
  trunk: 22,
  primary: 14,
  secondary: 11,
  tertiary: 8,
  residential: 5,
  unclassified: 5,
});

/** @const {number} Default lane count per road class when OSM has no `lanes`. */
export const LANES_BY_ROAD_CLASS = Object.freeze({
  motorway: 3,
  trunk: 3,
  primary: 2,
  secondary: 2,
  tertiary: 2,
  residential: 1,
  unclassified: 1,
});

// ─── Vision / detection ────────────────────────────────────────────────────

/** @const {string[]} Vehicle classes the detector reports. */
export const VEHICLE_CLASSES = Object.freeze([
  'car',
  'bus',
  'truck',
  'motorcycle',
  'emergency',
]);

/** @const {string[]} Emergency vehicle kinds the platform recognizes. */
export const EMERGENCY_VEHICLE_TYPES = Object.freeze([
  'ambulance',
  'fire-engine',
  'police',
]);

/** @const {number} Minimum detector confidence a detection is kept at. */
export const DETECTION_MIN_CONFIDENCE = 0.5;

/** @const {number} IoU above which two boxes are the same tracked vehicle. */
export const TRACK_IOU_THRESHOLD = 0.3;

/** @const {number} ms a track survives without a matching detection. */
export const TRACK_TTL_MS = 2500;

/** @const {number} Confidence a plate OCR result must reach to be readable. */
export const PLATE_MIN_CONFIDENCE = 0.9;

/** @const {number} Confidence a single plate character must reach. */
export const PLATE_MIN_CHAR_CONFIDENCE = 0.85;

/**
 * Confidence bands for fused emergency-vehicle identification.
 * @const {Object<string,number>}
 */
export const CONFIDENCE_BANDS = Object.freeze({
  high: 0.8,
  medium: 0.5,
  low: 0,
});

// ─── Violations, enforcement, privacy ──────────────────────────────────────

/** @const {string[]} Review states a violation can be in. */
export const REVIEW_STATES = Object.freeze([
  'pending',
  'approved',
  'rejected',
  'escalated',
]);

/**
 * Whether this deployment may issue an enforcement outcome without a human.
 *
 * Hard-wired off. A legally binding penalty requires an authorized enforcement
 * integration and a legal workflow, neither of which exists in a prototype;
 * the review queue is therefore mandatory. This constant exists so the
 * behaviour is discoverable, not so it can be flipped casually.
 * @const {boolean}
 */
export const AUTOMATED_ENFORCEMENT_ENABLED = false;

/** @const {number} Minutes an evidence record is retained (configurable). */
export const EVIDENCE_RETENTION_MINUTES = 60 * 24 * 30;

// ─── Roles ─────────────────────────────────────────────────────────────────

/** @const {Object<string,string>} Operator roles, least to most privileged. */
export const ROLES = Object.freeze({
  viewer: 'viewer',
  operator: 'operator',
  trafficControl: 'traffic-control',
  enforcementReview: 'enforcement-review',
  administrator: 'administrator',
});

/** @const {string[]} Capabilities the server gates endpoints on. */
export const CAPABILITIES = Object.freeze({
  viewCity: 'city:view',
  viewTraffic: 'traffic:view',
  controlSignals: 'signals:control',
  preemptSignals: 'signals:preempt',
  viewViolations: 'violations:view',
  viewPlate: 'violations:plate',
  reviewViolations: 'violations:review',
  runSimulation: 'simulation:run',
  readAudit: 'audit:read',
});

/** @const {Object<string,string[]>} Role → capabilities. */
export const ROLE_CAPABILITIES = Object.freeze({
  viewer: Object.freeze([CAPABILITIES.viewCity, CAPABILITIES.viewTraffic]),
  operator: Object.freeze([
    CAPABILITIES.viewCity,
    CAPABILITIES.viewTraffic,
    CAPABILITIES.runSimulation,
    CAPABILITIES.viewViolations,
  ]),
  'traffic-control': Object.freeze([
    CAPABILITIES.viewCity,
    CAPABILITIES.viewTraffic,
    CAPABILITIES.runSimulation,
    CAPABILITIES.viewViolations,
    CAPABILITIES.controlSignals,
    CAPABILITIES.preemptSignals,
  ]),
  'enforcement-review': Object.freeze([
    CAPABILITIES.viewCity,
    CAPABILITIES.viewViolations,
    CAPABILITIES.viewPlate,
    CAPABILITIES.reviewViolations,
  ]),
  administrator: Object.freeze(Object.values(CAPABILITIES)),
});

/** @const {string} Default role when no authenticated session exists. */
export const DEFAULT_ROLE = ROLES.trafficControl;

// ─── Display vocabulary (never colour alone) ───────────────────────────────

/**
 * The operating status vocabulary the 3D layer and the panels share. Each
 * entry carries a word, a glyph and a colour, so a status is never conveyed by
 * hue alone — the accessibility requirement is structural, not decorative.
 * @const {Object<string,{label:string,glyph:string,color:string,signal:string}>}
 */
export const STATUS_TOKENS = Object.freeze({
  flowing: Object.freeze({
    label: 'FLOWING',
    glyph: '▶',
    color: '#2ecc71',
    signal: 'green',
  }),
  slowing: Object.freeze({
    label: 'SLOWING',
    glyph: '⏸',
    color: '#f0b23e',
    signal: 'amber',
  }),
  congested: Object.freeze({
    label: 'CONGESTED',
    glyph: '⛔',
    color: '#e05252',
    signal: 'red',
  }),
  emergency: Object.freeze({
    label: 'EMERGENCY ROUTE',
    glyph: '✚',
    color: '#3aa0ff',
    signal: 'blue',
  }),
  incident: Object.freeze({
    label: 'INCIDENT',
    glyph: '⚠',
    color: '#b06bff',
    signal: 'purple',
  }),
  inactive: Object.freeze({
    label: 'INACTIVE',
    glyph: '○',
    color: '#e8f4f8',
    signal: 'white',
  }),
  fault: Object.freeze({
    label: 'FAULT',
    glyph: '✖',
    color: '#ff4d4d',
    signal: 'red',
  }),
});

/** @const {number} ms an operator confirmation request stays valid. */
export const CONFIRMATION_TTL_MS = 60_000;

/** @const {number} Maximum events retained in the live stream ring buffer. */
export const EVENT_RING_CAPACITY = 500;

/** @const {number} Maximum audit records retained. */
export const AUDIT_RING_CAPACITY = 2000;
